### ISSUE TITLE
Bug in reading identifiers [bug]

### ISSUE THREAD

**Issue by ArtemGolovko** [MAR-Lang/marlang#4]
Read the `var` identifier as `ar`

The code:
```
var = 1.2

var==1.3-0.1
```

The output:
```
Result: 
8
&{2 ar}
&{5 }
&{3 1.2}
&{2 ar}
&{18 }
&{3 1.3}
&{7 }
&{3 0.1}
```

**Comment by MadProbe** [comment]
I fixed this issue in #2 pull request.
The mistake was done by @WIDzer557 in Lexer.go in line 32: he forgot about backslash behind 'v' but he meant the vertical space characher
```go
		case ' ', '\n', '\t', 'v', '\r':
                              //^
                              //|
                              // The error
```
